### PR TITLE
Fix several visual glitches and missing tooltip

### LINKED ISSUE #1520: Small visual glitch when checking Venus large temple.
Image

Small visual glitch when checking Venus large temple progress.

### PR DESCRIPTION
**Pull request by eugenikus8**
1. Return artistic design and text for resolution greater than 720
2. FIX #1520
       - The window height for temples now defaults to HEIGHT_0_22_BLOCKS //352px;
4. FIX Granary Walker Permissions don't have tooltips  https://discord.com/channels/136544899339124736/1424305878160375822

### CODE REVIEW

File: src/window/building_info.c [hunk 1]
```diff
@@ -544,16 +525,18 @@ static void init(int grid_offset)
...
         case 11: context.height_blocks = 28; break;
-        case 12: context.height_blocks = 21; break;
+
         case 13: context.height_blocks = 15; break;
         default: context.height_blocks = 22; break;
     }
     adjust_height_for_storage_buildings(&context);
-    if (screen_height() <= 800) { // longest window is mars grand temple at 736px height
+    if ((screen_height() <= 600) ||
+        (screen_height() <= 720 && b->type == BUILDING_GRAND_TEMPLE_MARS)) { // longest window is mars grand temple at 736px height
```
Comment (Sephirex95) [inline src/window/building_info.c:539]: can we keep this value at 800, since we need to account for topbar height and it's scaling?

Comment (Sephirex95) [inline src/window/building_info.c:539]:
```suggestion
        (screen_height() <= 800 && b->type == BUILDING_GRAND_TEMPLE_MARS)) { // longest window is mars grand temple at 736px height
```

File: src/window/building_info.c [hunk 2]
```diff
@@ -1152,7 +1135,11 @@ static void get_tooltip(tooltip_context *c)
     } else if ((context.type == BUILDING_INFO_BUILDING && context.show_special_orders) || building_type_is_bridge(btype)) {
         //bridges are technically terrain, but they have special orders
         if (btype == BUILDING_GRANARY || btype == BUILDING_WAREHOUSE) {
-            window_building_get_tooltip_storage_orders(&group_id, &text_id, &translation);
+            if (context.show_special_orders == SPECIAL_ORDERS_ROADBLOCK) {
+                window_building_roadblock_get_tooltip_walker_permissions(&translation);
```
Comment (Sephirex95) [inline src/window/building_info.c:1139]: smooth solution!

**Comment by Sephirex95** [comment]
Oh, I just remembered - flavour text doesnt fit for Nymphaneums and Large Temples during construction, phase1 if i remember correctly. 

While you're here, could you please increase their window height to fit them?
